# roles/system/lang/tasks/main.yml
---
- name: set LANG=ja_JP.UTF-8 in /etc/sysconfig/i18n
  lineinfile:
    dest: /etc/sysconfig/i18n
    regexp: "^LANG="
    line: "LANG=ja_JP.UTF-8"
    backup: yes