---
- hosts: localhost
  gather_facts: no
  connection: local 
  vars:
    #your region
    region: ap-southeast-2
  tasks:
    - name: EC2 provisioning with provisioned IOPS EBS volume
      ec2:
        region: "{{ region }}"
        key_name: yan-key-pair-apsydney
        instance_type: t2.micro
        image: ami-dc361ebf
        group: sg_webserver_apsydney
        volumes:
          - device_name: /dev/sda1
            device_type: io1
            iops: 1000
            volume_size: 500
            delete_on_termination: true
