---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars_files:
    - staging_vpc_info
  vars:   
    region: ap-southeast-2    
    key: yan-key-pair-apsydney
    instance_type: t1.micro  
    image: ami-3bae3201
    prefix: staging
  tasks:  
    - name: NAT instance provisioning  
      ec2:
        region: "{{ region }}"  
        key_name: "{{ key }}"  
        instance_type: "{{ instance_type }}"    
        image: "{{ image }}"    
        wait: yes    
        group: "{{ prefix }}_sg_nat"  
        instance_tags:  
          Name: "{{ prefix }}_nat"  
          class: nat 
          environment: staging  
        id: nat_launch_02
        vpc_subnet_id: "{{ staging_subnet_public }}"
        source_dest_check: no
        wait: yes
      register: ec2
    - name: associate new EIP for the instance  
      tags: eip         
      ec2_eip:
        region: "{{ region }}"  
        instance_id: "{{ item.id }}"  
      with_items: ec2.instances   
      when: item.id is defined   
