---  
- hosts: localhost    
  gather_facts: no   
  connection: local  
  vars_files:
    - staging_vpc_info
  vars:  
    #your region  
    region: ap-southeast-2  
    #your ip address
    allowed_ip: 123.243.16.53/32
    #prefix for naming
    prefix: staging
    vpc_id: "{{ staging_vpc }}"
  tasks:  
    - name: create security group for jump box instance
      ec2_group:
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        #your security group name  
        name: "{{ prefix }}_sg_jumpbox"    
        description: security group for jump box
        rules:
          # allow ssh access from your ip address  
          - proto: tcp  
            from_port: 22  
            to_port: 22  
            cidr_ip: "{{ allowed_ip }}"  
        rules_egress:  
          - proto: all
            cidr_ip: 0.0.0.0/0  
