---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    #your region  
    region: ap-southeast-2    
  tasks:  
    - name: terminate instances
      ec2:
        region: "{{ region }}"  
        wait: yes  
        instance_ids: ['i-9e1e18a1', 'i-f61b1dc9', 'i-36272109', 'i-0b272134', 'i-0a272135']  
        state: absent  
