---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ec2_var.yml
  tasks:
    - name: Create ec2 instances.
      ec2: >
          keypair={{keypair}}
          group={{group}}
          instance_type={{instance_type}}
          image={{image}}
          region={{region}}
          count={{number}}
          wait=true
          zone={{zone}}
          instance_tags='{"Name":"ansible-test"}'
      register: ec2