---  
- hosts: localhost  
  gather_facts: no  
  connection: local   
  vars:  
    #your region  
    region: ap-southeast-2    
  tasks:  
    - name: EC2 provisioning with instance profile  
      ec2:
        region: "{{ region }}"  
        key_name: yan-key-pair-apsydney  
        instance_type: t2.micro  
        image: ami-dc361ebf      
        group: sg_webserver_apsydney
        instance_profile_name: app1