---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars_files:
    - staging_vpc_info
  vars:  
    region: ap-southeast-2    
    key: yan-key-pair-apsydney
    instance_type: t2.micro
    image: ami-dc361ebf
    prefix: staging
  tasks:  
    - name: web instance provisioning
      ec2:
        region: "{{ region }}"  
        key_name: "{{ key }}"
        instance_type: "{{ instance_type }}"  
        image: "{{ image }}"
        wait: yes    
        group: "{{ prefix }}_sg_web"
        instance_tags:
          Name: "{{ prefix }}_web"
          class: web
          environment: staging
        vpc_subnet_id: "{{ staging_subnet_public }}"
      register: ec2  
    - name: associate new EIP for the instance    
      ec2_eip:
        region: "{{ region }}"
        instance_id: "{{ item.id }}"
      with_items: ec2.instances
