---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    region: ap-southeast-2    
  tasks:  
    - name: launch instance
      ec2:
        region: "{{ region }}"  
        key_name: yan-key-pair-apsydney  
        instance_type: t1.micro  
        image: ami-6bf99c51  
        wait: yes    
        group: sg_webserver_apsydney
      register: ec2  
    - name: associate new EIP for the instance    
      ec2_eip:
        region: "{{ region }}"
        instance_id: "{{ item.id }}"
      with_items: ec2.instances
