---
- hosts: localhost
  gather_facts: no
  connection: local 
  vars:
    bucketname: yan001
  tasks:
    - name: upload file
      s3:
        bucket: "{{ bucketname }}"
        object: /backup/database/test.txt
        src: test.txt
        overwrite: no
        mode: put
